---
# handlers file for setup-apache-role

- name: starting httpd service
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"

- name: starting apache2 service
  service:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"


